services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=jdbc:mysql://mariadb-bd:3306/billing_republicadominicana
      - DATABASE_USERNAME=root
      - DATABASE_PASSWORD=sasa
      - FILESYSTEM_PATH=/app/file/
      - LOG_PATH=/app/logs
    depends_on:
      - db
    volumes:
      - app-file-volume:/app/file/
      - app-logs-volume:/app/logs

  db:
    container_name: mariadb-bd
    image: mariadb:10.11.6-jammy
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=sasa
      - MYSQL_DATABASE=billing_republicadominicana
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:
  app-file-volume:
  app-logs-volume: