spring:
  application:
    name: webservice-dgii-rd
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

springdoc:
  api-docs:
    path: /web-service-fe/v3/api-docs
  swagger-ui:
    path: /docs

swagger:
  info:
    title: Integración Facturación Electrónica DGII República Dominicana
    version: "2.0"
    description: API que permite integrar servicios DGII
  contact:
    name: Davis Coronado
    email: daviscoronadoalbines@gmail.com

logging:
  level:
    org.dcoronado.WebServiceDGIIRepublicaDominicana: DEBUG
    org.springframework: INFO

  file:
    path: ${LOG_PATH}

licencia:
  filesystem:
    basepath: ${FILESYSTEM_PATH}